apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ tpl .Values.resource.pullSecret.name . }}
  namespace: {{ tpl .Values.resource.pullSecret.namespace . }}
data:
  .dockerconfigjson: {{ .Values.registry.pullSecret.dockerConfigJSON | b64enc | quote }}
