version: 2.1

orbs:
  architect: giantswarm/architect@0.2.0

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            wget -q $(curl -sS -H "Authorization: token $RELEASE_TOKEN" https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
            chmod +x ./architect
            ./architect version
      - run:
          command: |
            ./architect build
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./architect deploy
            fi

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-docker:
          name: push-vault-exporter-to-docker
          image: "quay.io/giantswarm/vault-exporter"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          name: "package and push vault-exporter"
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: "vault-exporter"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
